debug: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: restaurant-service
            uri: lb://RESTAURANT-SERVICE
            predicates:
              - Path=/api/restaurant/**
            filters:
              - RewritePath=/api/restaurant/(?<segment>.*), /restaurant/${segment}

          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/orders/**
            filters:
              - RewritePath=/api/orders/(?<segment>.*), /orders/${segment}
server:
  port: 8092
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka
